# Generated by Django 4.0.1 on 2022-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northwind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
