# Generated by Django 4.0.1 on 2022-02-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northwind', '0002_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discontinued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_unit',
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_stock',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_on_order',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
