# Generated by Django 4.0.1 on 2022-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northwind', '0003_alter_product_discontinued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.SmallIntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
