# Generated by Django 4.0.1 on 2022-02-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('northwind', '0004_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
