# Generated by Django 4.0.1 on 2022-02-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('northwind', '0010_alter_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='northwind.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_per_unit',
            field=models.CharField(default=1, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='northwind.supplier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_in_stock',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_on_order',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
